### ISSUE TITLE
Issues with installing requirements

### ISSUE THREAD

**Issue by Ali-Hatami** [devaansh100/CLIPTrans#2]
Hi, Thanks for sharing the code, but unfortunately, it is impossible to run. It is a very bad practice when it is not possible even to install the requirements due to numerous version issues. Unfortunately, all the codes published in MMT on GitHub are very useless.

**Comment by devaansh100** [comment]
That's a bit surprising. Can you please tell me the exact error you are facing?

**Comment by devaansh100** [comment]
Hi, please try again. I have updated some dependencies, and it seems to be working for me.
