### ISSUE TITLE
transformers does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by dhawan98** [devaansh100/CLIPTrans#4]
Steps to recreate : 

git clone https://github.com/devaansh100/CLIPTrans.git
conda env create --file environment.yml
pip install -r requirements.txt 
cd transformers
pip install -e .

Obtaining file:///blue/daisyw/aashish.dhawan/CLIPTrans/transformers
ERROR: file:///blue/daisyw/aashish.dhawan/CLIPTrans/transformers does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

How do you get rid of this error?

**Comment by devaansh100** [comment]
Please look at the setup instructions in the README. I think this should disappear when you clone recursively.

**Comment by dhawan98** [comment]
Thank you! That fixed it.
